### ISSUE TITLE
Set up AWS to receive user input for adding devices

### ISSUE THREAD

**Issue by Mythois** [IT2901Nordic2024/backend#9]
**What user story is this feature related to?**
User Story #3
User Story Title: As a user I want to be able to connect to my device through a website

**What does this feature entail?**
Set up AWS to receive the data needed to add devices as "things" in AWS and save it

**Describe a suggested implentation**
__Fill out later__

**Task list**
Describe small, specific tasks that have to be completed for this feature to be fulfilled. Make the list longer or shorter as needed.
- [ ] step1
- [ ] step2
- [ ] step3
- [ ] ?????
- [ ] Profit

**Acceptance criteria**
Describe specific criteria for this feature request to be fulfilled, for instance specific styling.
- [ ] To be announced

**Additional context**
None provided

**Comment by EskildVeren** [comment]
Outdated issue
